config/routes.rb
Rails.application.routes.draw do
  get '/pdf', to: 'home#pdf'
  get '/prova', to: 'home#prova'
  get '/marcar/:id', to: 'home#marcar'
  get '/desmarcar/:id', to: 'home#desmarcar'
  get 'home/index'

  resources :questions

  resources :answers

  resources :lists

  root 'home#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :questions
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :list
  has_many :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)
    @answer.imagem.to_s
    respond_to do |format|
      if @answer.save
        format.html { redirect_to :back, notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:texto, :question_id, :imagem)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end

  def prova
    @perguntas = Question.where(prova: true)
  end

  def marcar
    @pergunta = Question.find(params[:id])
    @pergunta.prova = true
    @pergunta.save
    redirect_to "/prova"
  end

  def desmarcar
    @pergunta = Question.find(params[:id])
    @pergunta.prova = false
    @pergunta.save
    redirect_to "/prova"
  end

  def pdf

  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @perguntas = @list.questions.order(:numero)
    @answer = Answer.new
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:nome, :assunto)
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @answer = Answer.new
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to '/lists/'+@question.list.id.to_s, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:numero, :pergunta, :list_id, :prova)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_form.html.erb
<%= form_for(@answer) do |f| %>

  <div class="field">
    <%= f.label :texto %><br>
    <%= f.text_area :texto %>
  </div>
  <div class="field">
    <%#= f.hidden_field :question_id, :value => params[:id] %>
    <%= f.label :question_id %><br>
    <%= f.collection_select :question_id, Question.all.order(:numero), :id, (:pergunta) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<h1>Listing answers</h1>

<table>
  <thead>
    <tr>
      <th>Texto</th>
      <th>Question</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.texto %></td>
        <td><%= answer.question %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New answer</h1>

<%= render 'form' %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Texto:</strong>
  <%= @answer.texto %>
</p>

<p>
  <strong>Question:</strong>
  <%= @answer.question %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>

app/views/home/index.html.erb
<h2>Como usar:</h2>
<p><b>Passo 1</b>: Para colocar uma resposta, veja se já existe a pergunta cadastrada naquela lista, se não tiver, pode cadastrar a pergunta.</p>

<p><b>Passo 2</b>: Na lista de perguntas, procure qual delas vc quer responder e clique em Responder, na frente da pergunta. Uma pergunta pode ter várias respostas.</p>

<p><b>Passo 3</b>: Na hora da prova, se alguém editar uma pergunta e marcar o checkbox PROVA de alguma pergunta OU clicar no botão "COLOCAR!" será considerado que está pergunta está na prova, então ela aparecerá na página <a href="/prova">Prova</a>, a fim de facilitar a procura dos colegas.</p>

<p><b>Boa Sorte!</b></p>

<br><hr><br>

<p><b>OBS.:</b> SE alguma questão da prova não estiver na lista, faça a gentileza de Criar uma nova pergunta em qualquer lista, respondê-la, e marcar como questão da Prova como forma de agradecimento por este belíssimo esquema. E digo mais, é isso aí.</p>

app/views/home/pdf.html.erb
<h2>PDF das aulas</h2>

<hr>

<b>Unidade IV</b>:
<br>
<a href="https://www.sites.google.com/site/jbscinformatica/disciplinas/dwh/dwh_04a.pdf">dwh_04a.pdf</a>
<br>
<a href="https://www.sites.google.com/site/jbscinformatica/disciplinas/dwh/dwh_04b.pdf">dwh_04b.pdf</a>
<br>
<hr>
<br>
<b>Unidade V</b>:
<br>
<a href="https://www.sites.google.com/site/jbscinformatica/disciplinas/dwh/dwh_05a.pdf">dwh_05a.pdf  (Suite Pentaho)</a>
<br>
<a href="https://www.sites.google.com/site/jbscinformatica/disciplinas/dwh/dwh_05b.pdf">dwh_05b.pdf  (Pentaho BIserver)</a>
<br>
<a href="https://www.sites.google.com/site/jbscinformatica/disciplinas/dwh/dwh_05c.pdf">dwh_05c.pdf  (Pentaho PDI)</a>
<br>
<a href="https://www.sites.google.com/site/jbscinformatica/disciplinas/dwh/dwh_05d.pdf">dwh_05d.pdf  (Pentaho PRD)</a>
<br>
<a href="https://www.sites.google.com/site/jbscinformatica/disciplinas/dwh/dwh_05e.pdf">dwh_05e.pdf  (Pentaho PSW)</a>

app/views/home/prova.html.erb
<h1 style="text-align: center">Questões da prova!</h1>
<% @perguntas.each do |pergunta| %>
    <b><%= pergunta.pergunta %></b><br>
   <% i = 1 %>
    <% pergunta.answers.each do |resposta| %>
        <b><%= i %> - </b>
        <%= resposta.texto %><br>
        <% i += 1 %>
    <% end %>
    <% if pergunta.prova %>
        <%= link_to 'TIRAR!', '/desmarcar/'+pergunta.id.to_s, {remote: true, class: "btn btn-warning btn-sm"} %>
    <% else %>
        <%= link_to 'COLOCAR!', '/marcar/'+pergunta.id.to_s, {remote: true, class: "btn btn-primary btn-sm"} %>
    <% end %>
    <hr>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div >
      <ul class="nav nav-pills nav-justified">
        <a class="navbar-brand" href="/"></a>
        <li><%= link_to 'Home', '/' %></li>
        <li><%= link_to 'Lista1', '/lists/1' %></li>
        <li><%= link_to 'Lista2', '/lists/2' %></li>
        <li><%= link_to 'Lista3', '/lists/3' %></li>
        <li><%= link_to 'Lista4', '/lists/4' %></li>
        <li><%= link_to 'Lista5', '/lists/5' %></li>
        <li><%= link_to 'Lista6', '/lists/6' %></li>
        <li><%= link_to 'PDFs', pdf_path %></li>
        <li><%= link_to 'PROVA', prova_path %></li>
      </ul>

    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Listas</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="/bootstrap/css/bootstrap.css">
  <%#= javascript_include_tag 'application', 'data-no-turbolinks-track' => true %>
  <script type="text/javascript" src="/bootstrap/js/bootstrap.js"></script>

  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: 'layouts/header' %>

    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <%= yield %>
        </div>
      </div>
    </div>
</body>
</html>

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :assunto %><br>
    <%= f.text_area :assunto %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<h1>Listing lists</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Assunto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.nome %></td>
        <td><%= list.assunto %></td>
        <td><%= link_to 'Show', list %></td>
        <td><%= link_to 'Edit', edit_list_path(list) %></td>
        <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List', new_list_path %>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<h1 style="text-align: center">Lista <%= @list.id %></h1>

<p style="text-align: center">
<%= link_to "Criar Pergunta", new_question_path, class: "btn btn-default btn-lg" %>
</p>
<table class="table table-responsive table-bordered">
  <thead>
  <tr>
    <th>Numero</th>
    <th>Pergunta</th>
    <th colspan="2"></th>
  </tr>
  </thead>

  <tbody>
  <% @perguntas.each do |pergunta| %>
      <tr>
        <td><%= pergunta.numero %></td>
        <td><%= pergunta.pergunta %></td>
        <td><%= link_to 'Editar Pergunta', edit_question_path(pergunta), class: "btn btn-info btn-sm" %></td>
        <td>
          <%#= link_to 'PROVA!', '/', remote: true, class: "btn btn-primary btn-sm" %>
          <%#= link_to 'PROVA!', '/marcar/'+pergunta.id.to_s, {remote: true, class: "btn btn-primary btn-sm"} %>

          <% if pergunta.prova %>
              <%= link_to 'TIRAR!', '/desmarcar/'+pergunta.id.to_s, {remote: true, class: "btn btn-warning btn-sm"} %>
          <% else %>
              <%= link_to 'COLOCAR!', '/marcar/'+pergunta.id.to_s, {remote: true, class: "btn btn-primary btn-sm"} %>
          <% end %>



          <%#= link_to 'Destroy', pergunta, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %>
        </td>

      </tr>


            <% pergunta.answers.each do |resposta| %>
              <tr>
                <td><b>Resposta:</b></td>
                  <td colspan="3">
                    <%= resposta.texto%>
                    <br>
                        <% if resposta.imagem %>
                            <img src="<%= resposta.imagem %>"/>
                        <% end %>
                    </td>
              </tr>
            <% end %>


        <tr>
          <td colspan="4">
              <%= form_for(@answer) do |f| %>

                  <%= f.text_area :texto, style: "width: 70%;" %><br>
                  <b>Caminho da imagem</b>: <%= f.text_field :imagem, placeholder: "http://se.tiver/imagem.png"%>
                  <%= f.hidden_field :question_id, :value => pergunta.id %>
                  <br>
                  <%= f.submit "Reponder", class: "btn btn-success btn-sm"%>
              <% end %>
          </td>
        </tr>
  <tr><td colspan="4" style="background-color: #00394d"></td></tr>

  <% end %>
  </tbody>
</table>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :numero %><br>
    <%= f.number_field :numero %>
  </div>
  <div class="field">
    <%= f.label :pergunta %><br>
    <%= f.text_field :pergunta %>
  </div>
  <div class="field">
    <%= f.label :list_id %><br>
    <%= f.collection_select :list_id, List.all, :id, :nome %>
  </div>
  <div class="field">
    <%= f.label :prova %><br>
    <%= f.check_box :prova %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Listing questions</h1>

<table>
  <thead>
    <tr>
      <th>Numero</th>
      <th>Pergunta</th>
      <th>List</th>
      <th>Prova</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.numero %></td>
        <td><%= question.pergunta %></td>
        <td><%= question.list %></td>
        <td><%= question.prova %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Numero:</strong>
  <%= @question.numero %>
</p>

<p>
  <strong>Pergunta:</strong>
  <%= @question.pergunta %>
</p>

<p>
  <strong>List:</strong>
  <%= @question.list.nome %>
</p>
<hr>
<%= form_for(@answer) do |f| %>

    <%= f.text_area :texto %>

    <%= f.hidden_field :question_id, :value => @question.id %>

    <%= f.submit %>
<% end %>